### ISSUE TITLE
pysam ImportError

### ISSUE THREAD

**Issue by JeanMiCarter** [joshuagryphon/plastid#15]
Hi Joshua,

EDIT: Just noticed this was reported in #13 , will see if that solves it. Sorry!

I've installed plastid in a virtualenv as explained in your guide but I am getting an ImportError for a pysam library it seems? Do you have an idea what could be going wrong? Cheers!

```
(plastid_env) 133-33-123-5:~ jmcarter$ python -c "from plastid import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jmcarter/BioUnix/plastid_env/lib/python2.7/site-packages/plastid/__init__.py", line 40, in <module>
    from plastid.genomics.roitools import (GenomicSegment,
ImportError: dlopen(/Users/jmcarter/BioUnix/plastid_env/lib/python2.7/site-packages/plastid/genomics/roitools.so, 2): Library not loaded: @rpath/pysam/libctabixproxies.so
  Referenced from: /Users/jmcarter/BioUnix/plastid_env/lib/python2.7/site-packages/plastid/genomics/roitools.so
  Reason: image not found
```

**Comment by joshuagryphon** [comment]
Good eye! And thank you for checking the previous issues. I *just* pushed Plastid 0.4.8 to PyPI a few minutes ago, so upgrading should now work. I recommend trying the reinstall without using the `pip` cache, just in case:

```
$ pip install plastid --no-cache-dir --verbose | tee plastid_install_log.txt
```

Hopefully things will install correctly. If not, please comment on https://github.com/joshuagryphon/plastid/issues/13 and attach the log- I'll re-open that issue.

For now, I'm going to mark this bug as a duplicate and close it.
