### ISSUE TITLE
`crossmap` output file contains very short reads? 

### ISSUE THREAD

**Issue by AlicePsyche** [joshuagryphon/plastid#17]
Hi, 

I am new to ribosomal profiling, plastid is very helpful. I followed your guides on website, in masking genome section, I came across a problem.  The command I use:
`crossmap -k 26 --offset 12 --mismatches 2`
I found that there were many short reads(even 1 base) in the output bed file:
```
chr10   12      513     chr10:12-513(+) 0       +       12      12      0,0,0   1       501,    0,
chr10   13      514     chr10:13-514(-) 0       -       13      13      0,0,0   1       501,    0,
chr10   539     540     chr10:539-540(+)        0       +       539     539     0,0,0   1       1,      0,
chr10   540     541     chr10:540-541(-)        0       -       540     540     0,0,0   1       1,      0,
chr10   590     593     chr10:590-593(+)        0       +       590     590     0,0,0   1       3,      0,
chr10   591     594     chr10:591-594(-)        0       -       591     591     0,0,0   1       3,      0,
chr10   603     631     chr10:603-631(+)        0       +       603     603     0,0,0   1       28,     0,
chr10   604     632     chr10:604-632(-)        0       -       604     604     0,0,0   1       28,     0,
chr10   694     695     chr10:694-695(+)        0       +       694     694     0,0,0   1       1,      0,
chr10   695     696     chr10:695-696(-)        0       -       695     695     0,0,0   1       1,      0,
chr10   697     698     chr10:697-698(+)        0       +       697     697     0,0,0   1       1,      0,
chr10   698     699     chr10:698-699(-)        0       -       698     698     0,0,0   1       1,      0,
chr10   730     733     chr10:730-733(+)        0       +       730     730     0,0,0   1       3,      0,
chr10   731     734     chr10:731-734(-)        0       -       731     731     0,0,0   1       3,      0,
chr10   764     1534    chr10:764-1534(+)       0       +       764     764     0,0,0   1       770,    0,
chr10   765     1535    chr10:765-1535(-)       0       -       765     765     0,0,0   1       770,    0,
chr10   1656    1819    chr10:1656-1819(+)      0       +       1656    1656    0,0,0   1       163,    0,
chr10   1657    1820    chr10:1657-1820(-)      0       -       1657    1657    0,0,0   1       163,    0,
chr10   1821    1873    chr10:1821-1873(+)      0       +       1821    1821    0,0,0   1       52,     0,
chr10   1822    1874    chr10:1822-1874(-)      0       -       1822    1822    0,0,0   1       52,     0,
chr10   1875    1877    chr10:1875-1877(+)      0       +       1875    1875    0,0,0   1       2,      0,
chr10   1876    1878    chr10:1876-1878(-)      0       -       1876    1876    0,0,0   1       2,      0,
chr10   1986    1987    chr10:1986-1987(+)      0       +       1986    1986    0,0,0   1       1,      0,
chr10   1987    1988    chr10:1987-1988(-)      0       -       1987    1987    0,0,0   1       1,      0,
chr10   2140    2142    chr10:2140-2142(+)      0       +       2140    2140    0,0,0   1       2,      0,
chr10   2141    2143    chr10:2141-2143(-)      0       -       2141    2141    0,0,0   1       2,      0,
chr10   2143    2147    chr10:2143-2147(+)      0       +       2143    2143    0,0,0   1       4,      0,
chr10   2144    2148    chr10:2144-2148(-)      0       -       2144    2144    0,0,0   1       4,      0,
chr10   2198    2200    chr10:2198-2200(+)      0       +       2198    2198    0,0,0   1       2,      0,
chr10   2199    2201    chr10:2199-2201(-)      0       -       2199    2199    0,0,0   1       2,      0,
chr10   2256    2258    chr10:2256-2258(+)      0       +       2256    2256    0,0,0   1       2,      0,
chr10   2257    2259    chr10:2257-2259(-)      0       -       2257    2257    0,0,0   1       2,      0,
chr10   2303    2336    chr10:2303-2336(+)      0       +       2303    2303    0,0,0   1       33,     0,
chr10   2304    2337    chr10:2304-2337(-)      0       -       2304    2304    0,0,0   1       33,     0,
```

Did I miss some key parameters setting? Is it the right output file? Thanks in advance!

**Comment by joshuagryphon** [comment]
Hi @AlicePsyche ,

Thank you for your question. Each line in the BED file output from the `crossmap` should not be interpreted as a read, but rather, a *region* of the genome that would give rise to a multimapping read under the alignment criteria under which `crossmap` was run. So, if the regions that are output are only very short, that means that under your length and alignment criteria, most regions of the genome are unambigous. If you are using long reads (e.g. 75mers), that is likely to be the case.

It might help to describe the steps `crossmap` takes:

1. The genome is divided into reads of a given length (set with `-k` parameter)
2. Those reads are aligned back to the genome in `bowtie`. The number of times each read aligns is counted
3. Reads that align equally well to multiple parts of the genome are considered *multimappers*
4. For each multimapper, the corresponding genomic coordinate of the 5' end is found. That coordinate plus whatever value was set with the `--offset` parameter is marked as a *multimapping nucleotide*
5. Adjacent multimapping nucleotides are combined into *multimapping regions*

So, for example, if you created a crossmap using 26mers and with zero offset (`-k 26 --offset 0`), a 1-base long region in the output corresponds to a genomic location at which a 26mer composed of that base and the following 25 bases would multimap. 

Similarly, a 10-base long region corresponds to a set of 10 adjacent genomic locations whose corresponding set of 26mers (26mers whose 5' ends began at each of those 10 positions) would multimap.

Hope this helps. Please let me know if this makes sense!

Best,
Josh

**Comment by joshuagryphon** [comment]
Hi @AlicePsyche ,

I'm closing this issue. If my explanation above does not answer your question, or does not capture the issue somehow, please feel free to re-open.

Cheers,
Josh
