### ISSUE TITLE
 ‘phase_by_size’ command-line script problem with newer Numpy(1.13.1)

### ISSUE THREAD

**Issue by zyllifeworld** [joshuagryphon/plastid#18]
Hi,
I used the 'phase_by_size' script and it reports this error in '......../plastid/bin/phase_by_size.py' line 190 , in main：
>`counts = counts.reshape(len(counts)/3,3)`
>**TypeError**: 'float' object cannot be interpreted as an integer

![image](https://user-images.githubusercontent.com/25735636/29503886-2edfe48e-866e-11e7-9941-09cfc2eda913.png)

I found it happens because of __numpy.reshape__ (**Numpy(1.13.1)**) no longer support float as an input, but it works at **Numpy** 1.11.1. I changed the code and it works.

**Comment by joshuagryphon** [comment]
HI @zyllifeworld ,

Thank you for the heads up and for providing the solution! I'll fix this in time for the next version. I'll leave this issue open until it comes out.

Best,
Josh

**Comment by joshuagryphon** [comment]
Fixed in 3832e9d82dfc334cc4830ba6ecc85b23f035be9c

**Comment by lparsons** [comment]
Any chance you could release an updated version with this fix? Would be really nice for bioconda installs.

**Comment by joshuagryphon** [comment]
Yes, definitely. I think I can bump once #29  and any other tech debt due to upstream package updates are fixed (`pysam` has gone through some major changes, which I have not yet had a chance to test)
