### ISSUE TITLE
fatal error: 'stdio.h' file not found

### ISSUE THREAD

**Issue by bzeraee** [joshuagryphon/plastid#20]
"sudo pip install numpy pysam cython" command fails with the following error, 
....
......
  copying htslib/htslib/regidx.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/sam.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/synced_bcf_reader.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/tbx.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/thread_pool.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/vcf.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/vcf_sweep.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/vcfutils.h -> build/lib.macosx-10.10-intel-2.7/pysam/include/htslib/htslib
    running build_ext
    building 'pysam.libchtslib' extension
    creating build/temp.macosx-10.10-intel-2.7
    creating build/temp.macosx-10.10-intel-2.7/pysam
    creating build/temp.macosx-10.10-intel-2.7/htslib
    creating build/temp.macosx-10.10-intel-2.7/htslib/cram
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -Ipysam -I. -Ihtslib -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pysam/libchtslib.c -o build/temp.macosx-10.10-intel-2.7/pysam/libchtslib.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    In file included from pysam/libchtslib.c:4:
    /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:33:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-qWGO4X/pysam/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tPjAoV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-qWGO4X/pysam/

PLEASE SEE

**Comment by joshuagryphon** [comment]
Hi @bzeraee ,

Sorry to respond late on this, but this seems to be an issue with your system configuration rather than Plastid itself. `stdio.h` is part of the standard C library, which might not be installed on your system. [This entry on StackOverflow](https://stackoverflow.com/questions/28362994/where-is-my-stdio-h-in-mac) provides some suggestions, including typing the following into your terminal:

>xcode-select --install

Because this is an issue without outside packages rather than with Plastid itself, I'm going to close this issue. Please feel free to contact me if you have any further questions.

Cheers,
Josh
