### ISSUE TITLE
Requesting help on how to exclude codons from rfp density measurement..

### ISSUE THREAD

**Issue by PocketChangeJ** [joshuagryphon/plastid#22]
Hi,
First - thank you so much for sharing this tool! I'm relatively new to the data analysis world, and your tool helped me understand how to deal with my ribosome profiling results.
There is one problem I think I don't understand yet how to approach - specifically, I would like to count ribosome footprints over CDS, but effectively exclude several first and last codons. You do mention this briefly in your tutorial, however I'm not sure how to go about that - should I basically try creating a mask file that would mask the codons for all the transcripts, then use it during "cs generate"? I saw the example on the masking page for creating a mask for codons for a singe transcript in the demo bed file - so I supposed there should be a way to apply this to the whole bed/gtf file?
Thank you, 
PC

**Comment by joshuagryphon** [comment]
Closing this issue because no more questions received. Feel free to comment & re-open if you have further questions.
