### ISSUE TITLE
could not open alignment file - psite offset

### ISSUE THREAD

**Issue by AnaHowellsFerreira** [joshuagryphon/plastid#27]
Hi Joshua! 

We've been working on the psite (subprogram) but have encountered an issue and would appreciate
some feedback on how to handle this, since it is not very intuitive:

Here's were we started...
(https://plastid.readthedocs.io/en/latest/examples/p_site.html)

The gtf file was obtained from gramene. We did some filtering by removing cp (chloroplast), 
mithocondria (mt), tRNA and rRNA reads. 

Our bam file was obtained from STAR after multiple sequential alignments to isolate nuclear genomic reads, and they were sorted in indexed with Samtools: 

samtools sort --threads 27 ${in_file} -o sorted_${out_filename}
samtools index ${in_file} -b indexed_${out_filename}

After running the metagene generate on our maize reference and obtaining the *_rois.txt 
file required for the next step (psite), we tested on our indexed bam file but encountered 
the following warning messages:

"[E::hts_hopen] Failed to open file indexed_cp_genome_102617_RF-15Dark_Rep1_mergedAligned.out.bam
[E::hts_open_format] Failed to open file indexed_cp_genome_102617_RF-15Dark_Rep1_mergedAligned.out.bam
psite [2018-11-02 09:59:03]: Opening ROI file Zea_mays_orfs_rois.txt ...
psite [2018-11-02 09:59:04]: Opening count files indexed_cp_genome_102617_RF-15Dark_Rep1_mergedAligned.out.bam ...
Traceback (most recent call last):
  File "/packages/anaconda3/5.1.0/envs/plastid/bin/psite", line 11, in <module>
    load_entry_point('plastid==0.4.8', 'console_scripts', 'psite')()
  File "/packages/anaconda3/5.1.0/envs/plastid/lib/python3.5/site-packages/plastid/bin/psite.py", line 326, in main
    ga = ap.get_genome_array_from_args(args,printer=printer)
  File "/packages/anaconda3/5.1.0/envs/plastid/lib/python3.5/site-packages/plastid/util/scriptlib/argparsers.py", line 572, in get_genome_array_from_args
    count_files = [pysam.Samfile(X,"rb") for X in args.count_files]
  File "/packages/anaconda3/5.1.0/envs/plastid/lib/python3.5/site-packages/plastid/util/scriptlib/argparsers.py", line 572, in <listcomp>
    count_files = [pysam.Samfile(X,"rb") for X in args.count_files]
  File "pysam/libcalignmentfile.pyx", line 734, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 933, in pysam.libcalignmentfile.AlignmentFile._open
OSError: [Errno 8] could not open alignment file `indexed_cp_genome_102617_RF-15Dark_Rep1_mergedAligned.out.bam`: Exec format error"

The indexed bam files seem to be ok since we ran Subreads (featureCounts) on them, but for some reason, we cannot run plastid on them (counts_file argument, failed to open)

We appreciate your feedback and look forward to hearing back from you.

Ana and Mandie

**Comment by AnaHowellsFerreira** [comment]
Hi Joshua!
Thank you for your patience. We were able to find some help regarding this issue, which was related to our novice understanding of samtools. In order for Plastid to run the p site command, we must have the filename.bam.bai on the same directory as the filename.bam we are using to run the script. 
I hope that clarifies things for others in case someone else runs into this issue.
Thank you once again
Regards,
Ana and Mandie

**Comment by joshuagryphon** [comment]
Hi @AnaHowellsFerreira ,
I'm glad you were able to solve your problem! I am sorry for not replying earlier; this week has been quite hectic.

Please let me know if you run into other troubles!

Cheers,
Josh

**Comment by AnaHowellsFerreira** [comment]
Oh, no worries! We are enjoying learning about Plastid and quite amused by the program (only a few weeks into Ribo-seq, hehe!). 
Thank you for the reply and we'll keep you posted on any potential new issues. 
Have a good weekend and hopefully some rest from your hectic week  🙃 😊 
Ana
