### ISSUE TITLE
Plotting a metagene plot for two different samples at the same time

### ISSUE THREAD

**Issue by lundlab-kaltinel** [joshuagryphon/plastid#37]
Hi,
I am trying to generate a metagene plot for my samples `treated `and `untreated`. However I can only generate a plot having one of the samples ( either of them ) as in `count ` the input bam files get pooled together.
So the output looks as follows for the `'treated`' sample:
![metagene](https://user-images.githubusercontent.com/47667755/70143112-14a01980-169b-11ea-84da-c1ea9101ed09.png)

How can I add` 'untreated' `input to this plot to compare their trend for metagene distribution?

Thank you.

**Comment by joshuagryphon** [comment]
Hi @lundlab-kaltinel ,

I hope this message finds you well, and suspect you may have already found an answer to your question. But just in case this is still helpful, there is no easy way to do this within `plastid` itself.

What you can do, though, is take the following columns from `OUTBASE_metagene_profile.txt`, where `OUTBASE` is whatever naming argument you supplied to `metagene count`, and plot them together (e.g. using `matplotlib`, or in Excel, Google Sheets, et c):

- `x` : this is the coordinate relative to the start codon, plotted on the x-axis in plots generated by `metagene count`
- `metagene_average`: this is the profile that is plotted on the y-axis in the plots generated by `metagene count`

Hope this helps!

Best,
Josh
