### ISSUE TITLE
Incompatible with BioPython 1.78+

### ISSUE THREAD

**Issue by lparsons** [joshuagryphon/plastid#45]
The `GFF3_TranscriptAssembler` (and presumably other pieces of code) are not compatible with a change made to BioPython 1.78. Namely, the removal of the `Bio.Alphabet` module. This page (https://biopython.org/wiki/Alphabet) has more information, but TL;DR, just remove `Bio.Alphabet` and most code will still work.

```python
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by joshuagryphon** [comment]
Ahoy! @lparsons thank you for filing issues and supporting us all the way into 2020. Believe it or not, I'm prepping for another release, where we pumped the minimum BioPython requirements to 1.79. This release also drops support for Python versions 2.7–3.5. If you still use `plastid`, please stay tuned!

**Comment by bribibel** [comment]
Hi. I'm getting the ImportError for Bio.Alphabet when I download from conda. How do I remove Bio.Alphabet? Sorry - super new to computer science and am having difficulty installing with other methods.
