### ISSUE TITLE
the p site offset problem

### ISSUE THREAD

**Issue by z626093820** [joshuagryphon/plastid#48]
psite offset text show 26nt and 32 nt offset is 13,but in the figure there is empty,that's why?
![image](https://user-images.githubusercontent.com/37371455/142345833-3762b21c-9766-4de3-9b66-8f5514f2f1d1.png)
![image](https://user-images.githubusercontent.com/37371455/142345850-c2469ee0-d6c5-4871-8c09-a5c104eda14c.png)
thank you!

**Comment by joshuagryphon** [comment]
Yes- 13 is a default offset that is used when there are not enough reads available to estimate from the data. You can adjust this via a CLI argument called `--default` to the p-site script.
