### ISSUE TITLE
Procedure for P-site estimation using stop codon peaks

### ISSUE THREAD

**Issue by purplerainf** [joshuagryphon/plastid#5]
Hi, 

First of all, thank you for developing such a great tool.
It is easy to use and very helpful for my analysis.

I'd like to discuss my procedure for P-site estimation using stop codon peaks, not initiation peaks.

I am analyzing a ribosome profiling data, but it shows diminished initiation peaks due to poor stress response to lysis. So the P-site estimation using the initiation peaks generated noisy results.

Thus, I tried the P-site estimation using stop codon peaks. 
Your tutorial mentions it but suggests using another way instead of _psite_ script. 
(http://plastid.readthedocs.io/en/latest/examples/p_site.html#id13)

but I think- it could be accomplished by simply, 
   1) run _metagene generate_ with _--landmark stop_codon_ option (set R.O.I to the stop codons)
   2) run _psite_ script with the R.O.I.
   3) find peaks around 16-21nt, instead of 10-15nt to 5' end (+6nt then using initiation peaks. Because the stop codon would be at immediately downstream of A-site)

I think this is an easier way and actually, I found some peaks at 16~17nt for my data.
N. Ingolia's Sciences paper (Sciences 2009) also used this estimation. (See fig. 2B in the paper)
http://science.sciencemag.org/content/324/5924/218.figures-only

I look forward to hearing from you whether it makes sense or not.
Please correct me if I am wrong.

Thanks.

YY.

**Comment by joshuagryphon** [comment]
Dear YY,

Thank you for your note! I'm sorry for not getting back to you earlier- these past few weeks have included lots of travel and other work.

In any case, this procedure looks great, and, as far as usability goes, is a significant improvement upon what I currently suggest in the documentation. With your permission I'd like to include it in the documentation.

Please let me know what you think, and thank you again for writing.

Cheers,
Josh

**Comment by purplerainf** [comment]
I am glad to hear that it makes sense.
And, of course, it would be my pleasure if I can contribute to the documentation of your great tool. 

Best regards,
YY.

**Comment by joshuagryphon** [comment]
Wonderful! I'll include it in the next update. Thank you again for your suggestion!

Best,
Josh
