### ISSUE TITLE
Cython not running during `python setup.py build` : missing c_common.c file when building version 0.4.6

### ISSUE THREAD

**Issue by blaiseli** [joshuagryphon/plastid#6]
I downloaded the source from <https://files.pythonhosted.org/packages/source/p/plastid/plastid-0.4.6.tar.gz>, untarred it and tried to run `python setup.py build` in the obtained source directory. This resulted in the following error:

    gcc: error: /home/bli/src/plastid-0.4.6/plastid/genomics/c_common.c: No such file or directory

Is there some missing file or some missing building step somewhere?

**Comment by blaiseli** [comment]
The above was with python2. I experience no such issue with python3, so I guess all the files that should be distributed are present in the tarball, but some step is somehow not run properly during the build process in my python2 installation.

**Comment by joshuagryphon** [comment]
Hi blaiseli,

Thank you for your note! The `.c` files aren't even supposed to be in the sdist anymore, so I appreciate your bringing this to my attention.

As far as running `plastid` under Python 2, the good news is that it builds fine under Python 2 if you add a command line flag:
```
python setup.py build --recythonize
```

The long explanation is that the `.c` files in the sdist are generated from the `.pyx` files by Cython. The `.pyx` files are written to be compatible with Python 2.7+ and 3.3+, but the `.c` files will only be compatible with the version of Python that Cython was running under when the `.c` files were last generated (in this last case, Python 3). Adding `--recythonize` wipes all of the `.c` files and forces their regeneration. If running `setup.py` under Python 2, the new `.c.` files will be Python 2-compatible.

This is admittedly confusing. I thought I had removed the `.c` files from the source distribution already (in which case Cython will regenerate them without `--recythonize`, but they must still be creeping in. I'll fix this before the next release, and will also add a FAQ entry about this to the documentation in the mean time.

In any case, thank you again for bringing my attention to this, and please don't hesitate to write if you have more questions or find more odd behaviors.

Cheers,
Josh

**Comment by blaiseli** [comment]
Hi,

Thanks for the explanations.

It seems that the `--recythonize` is only valid for `setup.py develop`, not `setup.py build`. Anyway, `setup.py develop --recythonize` seems to automatically try to build and still complains about a missing `plastid/genomics/c_common.c`.

```
$ python setup.py develop --recythonize
running develop
Cythonize on
Cythonize on
Cythonizing
running recythonize
running clean
build_c_from_pyx: regenerating .c files from Cython
running egg_info
writing requirements to plastid.egg-info/requires.txt
writing plastid.egg-info/PKG-INFO
writing top-level names to plastid.egg-info/top_level.txt
writing dependency_links to plastid.egg-info/dependency_links.txt
writing entry points to plastid.egg-info/entry_points.txt
package init file 'kentUtils/__init__.py' not found (or not a regular file)
package init file 'kentUtils/src/inc/__init__.py' not found (or not a regular file)
package init file 'kentUtils/src/lib/__init__.py' not found (or not a regular file)
package init file 'kentUtils/samtabix/__init__.py' not found (or not a regular file)
Cythonize on
reading manifest file 'plastid.egg-info/SOURCES.txt'
writing manifest file 'plastid.egg-info/SOURCES.txt'
running build_ext
Cythonize on
Cythonizing
building 'plastid.genomics.c_common' extension
gcc -pthread -fno-strict-aliasing -O3 -march=native -fomit-frame-pointer -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bli/src/plastid-0.4.6/kentUtils/src/inc -I/home/bli/src/plastid-0.4.6/kentUtils/samtabix -I/home/bli/.local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include -I/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam -I/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/include/htslib -I/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/include/samtools -I/home/bli/include/python2.7 -c /home/bli/src/plastid-0.4.6/plastid/genomics/c_common.c -o build/temp.linux-x86_64-2.7/home/bli/src/plastid-0.4.6/plastid/genomics/c_common.o
gcc: error: /home/bli/src/plastid-0.4.6/plastid/genomics/c_common.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1
```


Cheers,

Blaise

**Comment by joshuagryphon** [comment]
Ok. That is a problem. I'll take a look at this tonight. Thank you for
checking!

**Comment by joshuagryphon** [comment]
Hi Blaise,

So, I haven't been able to replicate this in a Python 2.7 environment. But, from your screen output, it looks like Cython might not actually be running. When Cython runs, it creates some screen output below  `running recythonize`. This screen output that doesn't appear in your termcap:

```
running recythonize
running clean
build_c_from_pyx: regenerating .c files from Cython
Compiling /home/joshua/venv/newvenv/plastid-0.4.6/plastid/genomics/roitools.pyx because it changed.
Compiling /home/joshua/venv/newvenv/plastid-0.4.6/plastid/genomics/c_common.pyx because it changed.
Compiling /home/joshua/venv/newvenv/plastid-0.4.6/plastid/genomics/map_factories.pyx because it changed.
Compiling plastid/readers/bbifile.pyx because it changed.
Compiling plastid/readers/bigwig.pyx because it changed.
Compiling plastid/readers/bigbed.pyx because it changed.
[1/6] Cythonizing /home/joshua/venv/newvenv/plastid-0.4.6/plastid/genomics/c_common.pyx
[2/6] Cythonizing /home/joshua/venv/newvenv/plastid-0.4.6/plastid/genomics/map_factories.pyx
[3/6] Cythonizing /home/joshua/venv/newvenv/plastid-0.4.6/plastid/genomics/roitools.pyx
[4/6] Cythonizing plastid/readers/bbifile.pyx
[5/6] Cythonizing plastid/readers/bigbed.pyx
[6/6] Cythonizing plastid/readers/bigwig.pyx
```

Can you give me more details about your setup (OS, Python version, output of `pip list`, whether or not you are using conda)? 


I downloaded the sdist and created a naive Python 2.7 virtual environment, into which I only installed the minimal pre-reqs (numpy, pysam, cython). Invoking `python setup.py build` built everything fine. For example:

```
$ virtualenv newvenv
$ cd newvenv && source bin/activate
$ pip install numpy pysam cython
$ tar -zxvf ~/Downloads/plastid-0.4.6.tar.gz
$ cd plastid-0.4.6
$ python setup.py builld
$ find . -name "*so"
```

As expected, this yields:
```
./build/lib.linux-x86_64-2.7/plastid/genomics/map_factories.so
./build/lib.linux-x86_64-2.7/plastid/genomics/c_common.so
./build/lib.linux-x86_64-2.7/plastid/genomics/roitools.so
./build/lib.linux-x86_64-2.7/plastid/readers/bigwig.so
./build/lib.linux-x86_64-2.7/plastid/readers/bbifile.so
./build/lib.linux-x86_64-2.7/plastid/readers/bigbed.so
```

Cheers,
Josh

**Comment by blaiseli** [comment]
Hi Joshua,

I don't use conda.

OS and python version:

```
$ uname -a
Linux naples 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.12
```

`pip list` output:

```
$ pip list
apsw (3.8.11.1.post1)
astroid (1.4.4)
backports.shutil-get-terminal-size (1.0.0)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.5.1)
biopython (1.68)
chardet (2.3.0)
CherryPy (3.5.0)
chr-helpers (9999)
cssselect (0.9.1)
cssutils (1.0)
cutadapt (1.11)
cycler (0.10.0)
Cython (0.24.1)
decorator (4.0.10)
deepTools (2.3.1)
defusedxml (0.4.1)
DendroPy (4.0.3)
dnspython (1.12.0)
ete2 (2.3.10)
ete3 (3.0.0b35)
feedparser (5.1.3)
html5lib (0.999)
HTSeq (0.6.1p1)
husl (4.0.3)
iotop (0.6)
ipython (5.1.0)
ipython-genutils (0.1.0)
lazy-object-proxy (1.2.1)
logilab-common (1.1.0)
lxml (3.5.0)
MACS2 (2.1.0.20150420)
Magic-file-extensions (0.2)
Markdown (2.6.6)
matplotlib (1.5.1)
mechanize (0.2.5)
netifaces (0.10.4)
numpy (1.11.2)
numpydoc (0.6.0)
p4 (1.2.0.-2016-05-03-)
pandas (0.19.1)
pathlib2 (2.1.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (8.1.2)
prompt-toolkit (1.0.7)
ptyprocess (0.5.1)
pybedtools (0.7.4)
pyBigWig (0.2.8)
pycrypto (2.6.1)
Pygments (2.1.3)
pygobject (3.20.0)
pyliblzma (0.5.3)
pylint (1.5.2)
pyparsing (2.1.5)
pysam (0.9.1.4)
Pyste (0.9.10)
python-dateutil (2.5.3)
pytz (2016.7)
PyYAML (3.11)
repoze.lru (0.6)
Routes (2.2)
scikit-learn (0.18)
scipy (0.18.1)
scour (0.32)
seaborn (0.7.1)
setuptools (0.6rc11)
simplegeneric (0.8.1)
six (1.10.0)
SOAPpy (0.12.22)
termcolor (1.1.0)
traitlets (4.2.2)
twobitreader (3.1.4)
uTidylib (0.2)
wcwidth (0.1.7)
WebOb (1.5.1)
wheel (0.29.0)
wrapt (1.8.0)
wstools (0.4.3)
xlrd (0.9.4)
yapf (0.13.2)
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Note that I actually do not install packages through pip, but by manually using `setup.py` so that I can add custom compiler flags. Maybe this could cause some problems. So don't wast too much time with this.

The build inside a virtual env seems to work.

I just noted the following warning:

    warning: plastid/genomics/map_factories.pyx:523:35: Index should be typed for more efficient access

and this:

    skipping '/home/bli/newvenv/src/plastid-0.4.6/plastid/genomics/c_common.c' Cython extension (up-to-date)

Is this expected ? Before running build, this file doesn't exist.

**Comment by blaiseli** [comment]
Hi again,

Just to let you know another thing I noticed, this time while building and installing for python3:

```
byte-compiling /home/bli/.local/lib/python3.5/site-packages/kentUtils/samtabix/tabix.py to tabix.cpython-35.pyc
  File "/home/bli/.local/lib/python3.5/site-packages/kentUtils/samtabix/tabix.py", line 84
    print line
             ^
SyntaxError: Missing parentheses in call to 'print'
```

Cheers,

Blaise

**Comment by joshuagryphon** [comment]
Hi Blaise,

Thank you for the detailed information. Your system config looks correct, and installing manually from each `setup.py` should work fine. I'm not sure why Cython doesn't appear to be running.

I'm really scratching my head here, but one possibility is that it might not be finding the headers it needs. What happens with `"import numpy; numpy.get_include()"` and, simlarly `import pysam; pysam.get_include()`? Do they point to valid folders, and are those folders full of files? Also, do you have `zlib` headers installed?

For the build warnings, the first two are expected: in the first case, using dynamic typing provides a convenience to users; for the second, its just a note generated by Cython that there is no need to re-build `c_common.c` when the second `.pyx` file imports from `c_common` if it is up to date.

The third error was a bit of a surprise; it comes from a Python file included with the samtabix dependencies, but that is not actually used by Plastid, and that I had not intended to include. It isn't in the `git` repo, but must have been included when I made the `sdist`. It should be safe to just remove it from the source folder before calling `python setup.py ...`.

Thanks again,
Josh

**Comment by blaiseli** [comment]
Hi Joshua,

Here is the output of the `get_include()` commands:
```
Python 2.7.12 (default, Aug 22 2016, 19:18:33) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy; numpy.get_include()
'/home/bli/.local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include'
>>> import pysam; pysam.get_include()
['/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam', '/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/include/htslib', '/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/include/samtools']
```

All these directories exist.
`/home/bli/.local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include` just contains a `numpy` directory, which contains ".h" files
The other three all contain ".h" files.

I have various `zlib.h` files, among others:

* `/home/bli/.local/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/include/samtools/win32/zlib.h`
* `/home/bli/include/zlib.h`
* `/usr/include/zlib.h`

Strangely, the "SyntaxError" doesn't seem to appear any more.

**Comment by joshuagryphon** [comment]
Hmmm...that all looks good. Are you able to install other sdists that require Cython (and don't include pre-made `.c` files) via `python setup.py ...`? If yes, then there might be something I can add to `setup.py` to get things working in this context, which would be useful to know. If no, then it might be a Cython issue that comes up in this specific setup
