### ISSUE TITLE
Incompatibility with Pysam 0.10.0: Cythonize error while compiling map_factories.pyx

### ISSUE THREAD

**Issue by Cobrec11** [joshuagryphon/plastid#8]
Hi Josh,

i am trying to install plastid in an Ubuntu 14.04.5 environment using python 2.7. All dependencies are installed correctly to my knowledge. During installation the setup fails because the cython compiling of map_factories fails. 

```
kevinklann@pqc-Virtual-Machine:~/Downloads/plastid-0.4.6$ python setup.py install
running install
Could not find .c files. Regenerating via recythonize.
Cythonizing
running recythonize
running clean
clean_c_files: removing /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/map_factories.c ...
clean_c_files: removing /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/c_common.c ...
build_c_from_pyx: regenerating .c files from Cython
/home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/map_factories.pyx: cannot find cimported module 'pysam.calignmentfile'
Compiling /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/map_factories.pyx because it changed.
Compiling /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/roitools.pyx because it changed.
Compiling /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/c_common.pyx because it changed.
Compiling plastid/readers/bbifile.pyx because it changed.
Compiling plastid/readers/bigwig.pyx because it changed.
Compiling plastid/readers/bigbed.pyx because it changed.
[1/6] Cythonizing /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/c_common.pyx
[2/6] Cythonizing /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/map_factories.pyx

Error compiling Cython file:
------------------------------------------------------------
...

import numpy as np
cimport numpy as np
cimport cython

from pysam.calignmentfile cimport AlignedSegment
^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:134:0: 'pysam/calignmentfile.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

import numpy as np
cimport numpy as np
cimport cython

from pysam.calignmentfile cimport AlignedSegment
^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:134:0: 'pysam/calignmentfile/AlignedSegment.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
            raise ValueError("Alignment size filter: min read length must be >= 1. Got %s" % min)

        self.min_ = min
        self.max_ = max

    def __call__(self,AlignedSegment read not None):
                     ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:812:22: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            raise ValueError("Alignment size filter: min read length must be >= 1. Got %s" % min)

        self.min_ = min
        self.max_ = max

    def __call__(self,AlignedSegment read not None):
                     ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:812:22: Only Python type arguments can have 'not None'

Error compiling Cython file:
------------------------------------------------------------
...

        cdef list reads_out = []
        cdef list read_positions

        cdef:
            AlignedSegment read
           ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:233:12: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            np.ndarray[LONG_t,ndim=1] count_array = np.zeros(seg_len,dtype=LONG)
            long [:] count_view = count_array

            list reads_out = []
            list read_positions
            AlignedSegment read
           ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:328:12: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            np.ndarray[LONG_t,ndim=1] count_array = np.zeros(seg_len,dtype=LONG)
            long [:] count_view = count_array

            list reads_out = []
            list read_positions
            AlignedSegment read
           ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:422:12: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            int no_offset_length
            int do_no_offset_warning = 0

            int            read_length, offset
            long           p_site
            AlignedSegment read
           ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:596:12: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            int min_length             = self.min_length

            list reads_out             = []
            int read_length, offset, p_site

            AlignedSegment read
           ^
------------------------------------------------------------

plastid/genomics/map_factories.pyx:734:12: 'AlignedSegment' is not a type identifier
warning: plastid/genomics/map_factories.pyx:523:35: Index should be typed for more efficient access
Traceback (most recent call last):
  File "setup.py", line 591, in <module>
    test_suite        = "nose.collector",
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 437, in run
    self.run_command(CYTHONIZE_COMMAND)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 485, in finalize_options
    extensions = cythonize(ext_modules,compiler_directives=CYTHON_ARGS)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 934, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1056, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/kevinklann/Downloads/plastid-0.4.6/plastid/genomics/map_factories.pyx

```
The same is true when i try to install it via pip. 

Hope you can help me.

Cheers,

Kevin

**Comment by Cobrec11** [comment]
```
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
biopython==1.68
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
cycler==0.10.0
Cython==0.25.2
debtagshw==0.1
defer==1.0.6
dirspec==13.10
duplicity==0.6.23
functools32==3.2.3.post2
html5lib==0.999
httplib2==0.8
lockfile==0.8
lxml==3.3.3
mageck==0.5.5
matplotlib==2.0.0
numpy==1.12.0
oauthlib==0.6.1
oneconf==0.3.7.14.4.1
PAM==0.4.2
pandas==0.19.2
pexpect==3.1
Pillow==2.3.0
piston-mini-client==0.7.5
pycrypto==2.6.1
pycups==1.9.66
pygobject==3.12.0
pyOpenSSL==0.13
pyparsing==2.1.10
pysam==0.10.0
pyserial==2.6
pysmbc==1.0.14.1
python-apt===0.9.3.5ubuntu2
python-dateutil==2.6.0
python-debian===0.1.21-nmu2ubuntu2
pytz==2016.10
pyxdg==0.25
reportlab==3.0
requests==2.2.1
scipy==0.18.1
sessioninstaller==0.0.0
six==1.10.0
software-center-aptd-plugins==0.0.0
ssh-import-id==3.21
subprocess32==3.2.7
system-service==0.1.6
termcolor==1.1.0
Twisted-Core==13.2.0
Twisted-Web==13.2.0
twobitreader==3.1.4
unity-lens-photos==1.0
urllib3==1.7.1
xdiagnose===3.6.3build2
zope.interface==4.0.5
```

**Comment by Cobrec11** [comment]
By accident i found out, that the setup is not compatible with the pysam 0.10.0 version. I tried to install it on another computer with pysam 0.8.4. and it worked fine. After downgrading from 0.10.0 to 0.8.4 everything works fine.

**Comment by joshuagryphon** [comment]
Hi Kevin,

Thank you for the heads up, and all of the detailed information! I'm going to go ahead and re-open this- supporting updates to Pysam (and other software) is critical. 

I'll get started on this soon. 

Cheers,
Josh

**Comment by tfmartinez** [comment]
I seem to be having the same issue compiling map_factories while installing plastid, even when using virtualenv and using pysam 0.8.4. Any thoughts on what might be causing the issue?


Successfully installed plastid-0.4.6
(venv) tfm:virtual_test tfmartinez$ python -c "from plastid import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tfmartinez/Desktop/virtual_test/venv/lib/python2.7/site-packages/plastid/__init__.py", line 40, in <module>
    from plastid.genomics.genome_array import BAMGenomeArray, BigWigGenomeArray, GenomeArray, SparseGenomeArray, variable_five_prime_map, five_prime_map, center_map, three_prime_map
  File "/Users/tfmartinez/Desktop/virtual_test/venv/lib/python2.7/site-packages/plastid/genomics/genome_array.py", line 215, in <module>
    from plastid.genomics.map_factories import *
  File "cfaidx.pxd", line 37, in init plastid.genomics.map_factories (/private/var/folders/gz/pkknbhl97p7gvwtzx3g9rll80000gq/T/pip-build-SVTgDx/plastid/plastid/genomics/map_factories.c:25365)
ValueError: pysam.cfaidx.FastaFile has the wrong size, try recompiling

**Comment by joshuagryphon** [comment]
Hi tfmartinez,

I think this is a different issue. The message `ValueError: pysam.cfaidx.FastaFile has the wrong size, try recompiling` comes up when Plastid is linked against a different version of Pysam than found in its runtime environment. This happens often when people use conda, because conda's sandboxes are not always inherited by the subshells that distutils creates to compile python extensions. That said, building and running Plastid inside the same `virtualenv` takes care of this.

Can you tell me:

 1. Details of your setup (OS, system Python version, virtualenv Python version et c)
 2. How you installed Plastid (from PyPI via `pip` or via `easy_install`? from source via `pip` or via manual calls to `python setup.py ...`) and which version (from PyPI, from a specific git branch)? 
 3. What happens within your `virtualenv` when you type `python -c 'import pysam; print(pysam.__version__)'` and what happens outside your `virtualenv` when you type `python -c 'import pysam; print(pysam.__version__)'`?
 4. Whether you have other Python environments installed (e.g. via conda somewhere)?
 5. Output of `pip list`, when run inside your virtualenv?

Depending upon your answers, I might open a new issue for you, or merge the discussion into another, similar issue.

Thanks & best,
Josh

**Comment by tfmartinez** [comment]
Hi Josh,

Thanks for the speedy reply. I appreciate any advice you can offer.

1. I'm on OS X, El Capitan.
System python is 2.7.13--installed with homebrew (GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)).
Python is 2.7.10 in the virtualenv.

2. Installed plastid-0.4.6 in virtualenv using pip. First ran pip install numpy pysam==0.8.4 cython.

3. Inside:
(venv) tfm:virtual_test tfmartinez$ python -c 'import pysam; print(pysam.__version__)'
0.8.4

Outside:
tfm:virtual_test tfmartinez$ python -c 'import pysam; print(pysam.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pysam

Inside: pip freeze
appdirs==1.4.0
biopython==1.68
cycler==0.10.0
Cython==0.25.2
functools32==3.2.3.post2
matplotlib==2.0.0
numpy==1.12.0
packaging==16.8
pandas==0.19.2
plastid==0.4.6
pyparsing==2.1.10
pysam==0.8.4
python-dateutil==2.6.0
pytz==2016.10
scipy==0.18.1
six==1.10.0
subprocess32==3.2.7
termcolor==1.1.0
twobitreader==3.1.4

4. I was guilty of having conda installed originally, but I uninstalled it when I saw other posts about having issues with conda and pip. Anaconda folder is gone and its directories removed from my bash_profile. This could still be causing a lingering issue, though.

5. Inside: pip list
(venv) tfm:virtual_test tfmartinez$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.0)
biopython (1.68)
cycler (0.10.0)
Cython (0.25.2)
functools32 (3.2.3.post2)
matplotlib (2.0.0)
numpy (1.12.0)
packaging (16.8)
pandas (0.19.2)
pip (9.0.1)
plastid (0.4.6)
pyparsing (2.1.10)
pysam (0.8.4)
python-dateutil (2.6.0)
pytz (2016.10)
scipy (0.18.1)
setuptools (34.1.1)
six (1.10.0)
subprocess32 (3.2.7)
termcolor (1.1.0)
twobitreader (3.1.4)
wheel (0.30.0a0)

Outside:  pip list
tfm:virtual_test tfmartinez$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.0)
cycler (0.10.0)
functools32 (3.2.3.post2)
numexpr (2.6.2)
packaging (16.8)
pbr (1.10.0)
pip (9.0.1)
pyparsing (2.1.10)
python-dateutil (2.6.0)
pytz (2016.10)
setuptools (34.1.1)
six (1.10.0)
stevedore (1.20.0)
subprocess32 (3.2.7)
termcolor (1.1.0)
twobitreader (3.1.4)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wheel (0.29.0)

--tfm

**Comment by tfmartinez** [comment]
I also forgot to mention that I have pypy installed as well. However, there is no pysam module there either.

tfm:virtual_test tfmartinez$ pypy -c 'import pysam; print(pysam.version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pysam

**Comment by joshuagryphon** [comment]
Hi folks!

@tfmartinez Thank you for the update.To make sure I understand, you were able to build by rolling back? That's strange to me, because 0.4.6 works with 0.8.4 in my test environments.

Either way, I just pushed an update to the `develop` branch for Plastid to work with Pysam 0.10.0. It maintains backward compatibility with earlier Pysam versions, too.

 `develop` is passing all of its unit tests, so I recommend installing that.  The main changes in 0.4.6 were BigWig and improved BigBed support, a bunch of improvements to command-line scripts, and simplification/standardization of a lot of the APIs. I'm going to wrap these into an official release as soon as I have time. For now, I'd recommend installing the develop branch rather than rolling back.

**Comment by tfmartinez** [comment]
Hi Josh,

That is correct. In my virtualenv, rolling back to plastid 0.4.5 does not have the same compiling error show up with pysam 0.8.4 and I am able to import plastid just fine.

As for the `develop` branch, I tried running `setup.py` but ran into an error during building:

`can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file`

I've moved away from running plastid on my Mac, however, and have plastid 0.4.6 working well with pysam 0.8.4 on a linux box, so it's no problem.

Thanks!

tfm

**Comment by joshuagryphon** [comment]
Ok. In that case I'm going to try to get my hands on a Mac for some in-depth testing. I haven't seen the `can't link with bundle ... ` error message before

I'm going to cautiously close this because the original issue of incompatibility with Pysam 0.10.0 has been resolved by rewriting some imports to additionally work with Pysam's renamed library internals.

Please open a new issue if you continue to see additional weirdness, and thank you again for your help!
